### ISSUE TITLE
Environment Connection Issue 

### ISSUE THREAD

**Issue by JD-ETH** [facebookresearch/CompilerGym#120]
## 🐛 Bug

The port connection breaks after refreshing the environment multiple times. 

## To Reproduce

1. When executing the environment multiple times in [here](https://github.com/JD-ETH/CompilerGym/blob/feature/tabular-q/examples/tabular_q.py#L7) 
2. Enabled debug flag by export COMPILER_GYM_DEBUG=3

Output: 
```
I0304 21:05:27.817211 341052928 RunServiceImpl.h:45] LLVM service listening on 64067
I0304 21:05:27.817638 341052928 RunServiceImpl.h:56] Wrote /Users/jdguo/.cache/compiler_gym/service-2021-03-04T21:05:27.798781-f3f9/port.txt
I0304 21:05:28.011813 4583357952 connection.py:325] Connection attempt 1 =
I0304 21:05:28.135140 4583357952 connection.py:325] Connection attempt 2 =
I0304 21:05:28.285143 4583357952 connection.py:325] Connection attempt 3 =
I0304 21:05:28.463429 4583357952 connection.py:325] Connection attempt 4 =
I0304 21:05:28.671988 4583357952 connection.py:325] Connection attempt 5 =
I0304 21:05:28.924084 4583357952 connection.py:325] Connection attempt 6 =
I0304 21:05:29.225484 4583357952 connection.py:325] Connection attempt 7 =
I0304 21:05:29.589740 4583357952 connection.py:325] Connection attempt 8 =
I0304 21:05:30.024158 4583357952 connection.py:325] Connection attempt 9 =
I0304 21:05:30.543173 4583357952 connection.py:325] Connection attempt 10 =
I0304 21:05:31.168564 4583357952 connection.py:325] Connection attempt 11 =
W0304 21:05:31.173238 4583357952 connection.py:529] TimeoutError Failed to connect to RPC service after 10.0 seconds(11 attempts made) (attempt 3)
Traceback (most recent call last):
  File "tabular_q.py", line 138, in <module>
    app.run(main)
  File "/Users/jdguo/.local/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/jdguo/.local/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tabular_q.py", line 122, in main
    train(q_table)
  File "tabular_q.py", line 77, in train
    env = get_env()
  File "tabular_q.py", line 49, in get_env
    return env_from_flags(benchmark_from_flags())
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/site-packages/compiler_gym/util/flags/env_from_flags.py", line 115, in env_from_flags
    env = gym.make(
  File "/Users/jdguo/.local/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/Users/jdguo/.local/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/Users/jdguo/.local/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/site-packages/compiler_gym/envs/llvm/llvm_env.py", line 75, in __init__
    super().__init__(
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/site-packages/compiler_gym/envs/compiler_env.py", line 213, in __init__
    self.service = service_connection or CompilerGymServiceConnection(
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 463, in __init__
    self._establish_connection()
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 474, in _establish_connection
    self.connection = self._create_connection(self.endpoint, self.opts, self.logger)
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 531, in _create_connection
    raise TimeoutError(
TimeoutError: Failed to create connection to compiler_gym-llvm-service after 10.1 seconds (3/5 attempts made)
I0304 21:05:31.204999 76095488 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.226480 4960256 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.231853 193499136 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.237021 232955904 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.242280 119836672 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.247112 265076736 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.252007 68136960 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.254989 70819840 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.259858 96407552 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]
I0304 21:05:31.280346 90673152 LlvmService.cc:106] Step 5 EndSession(benchmark://cBench-v0/dijkstra), [0]`
```

## Expected behavior

Connection shouldn't crash. 

## Environment

Please fill in this checklist:

- CompilerGym: up to date with development
- How you installed CompilerGym (conda, pip, source): pip in conda env
- OS: Mac
- Python version: 3.8
- Build command you used (if compiling from source): not from source 
- GCC/clang version (if compiling from source):
- Bazel version (if compiling from source):
- Versions of any other relevant libraries:

You may use the PyTorch
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
to generate most of this information. You can get the script and run it with:

```sh
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by ChrisCummins** [comment]
Hi @JD-ETH, thanks for the report! That's a strange error. In these first two lines of output you posted:

```
I0304 21:05:27.817211 341052928 RunServiceImpl.h:45] LLVM service listening on 64067
I0304 21:05:27.817638 341052928 RunServiceImpl.h:56] Wrote /Users/jdguo/.cache/compiler_gym/service-2021-03-04T21:05:27.798781-f3f9/port.txt
```

those are logging messages from the service showing that it has correctly launched and is ready to go. However the rest of the output shows that the frontend client was for some reason unable to connect to it.

FWIW, the script runs fine on my machine:

```
$ python tabular_q.py
Running episode 0, current Q table:  {((105, 48, 410), 1): 9.700000000000001, ((83, 27, 313), 0): 0, ((83, 27, 313), 1): 0.0, ((83, 27, 313), 2): 3.4000000000000004, ((71, 24, 279), 0): 0.0, ((71, 24, 279), 1): 0.0, ((71, 24, 279), 2): 0}
Newly added Q entries 7, averaged diff NaN
Running episode 10, current Q table:  {((105, 48, 410), 1): 68.75874610610002, ((83, 27, 313), 0): 0, ((83, 27, 313), 1): 0.0, ((83, 27, 313), 2): 23.33043973294, ((71, 24, 279), 0): 0.0, ((71, 24, 279), 1): 0.0, ((71, 24, 279), 2): 0.0, ((105, 48, 410), 0): 20.403734000000004}
Newly added Q entries 1, averaged diff 11.284169405577146
...
Running episode 980, current Q table:  {((105, 48, 410), 1): 130.99999999999991, ((83, 27, 313), 0): 33.97717823837385, ((83, 27, 313), 1): 33.98143232324701, ((83, 27, 313), 2): 33.99999999999998, ((71, 24, 279), 0): 0.0, ((71, 24, 279), 1): 0.0, ((71, 24, 279), 2): 0.0, ((105, 48, 410), 0): 130.29582034398027, ((105, 48, 410), 2): 130.4020365941934, ((93, 45, 331), 0): 51.924309926167645, ((93, 45, 331), 1): 17.882800000000003, ((93, 45, 331), 2): 25.409881709405973}
Newly added Q entries 0, averaged diff 0.006903417540729724
Running episode 990, current Q table:  {((105, 48, 410), 1): 130.99999999999991, ((83, 27, 313), 0): 33.97717823837385, ((83, 27, 313), 1): 33.98328909092231, ((83, 27, 313), 2): 33.99999999999998, ((71, 24, 279), 0): 0.0, ((71, 24, 279), 1): 0.0, ((71, 24, 279), 2): 0.0, ((105, 48, 410), 0): 130.42961447862405, ((105, 48, 410), 2): 130.4020365941934, ((93, 45, 331), 0): 51.924309926167645, ((93, 45, 331), 1): 17.882800000000003, ((93, 45, 331), 2): 25.409881709405973}
Newly added Q entries 0, averaged diff 0.011304241859923181
Resulting sequence:  -mem2reg,-newgvn,-sroa,-mem2reg,-sroa total reward131.0
```

I think to make progress we'll need to be able to run development builds so that we can to improve the error logging. Can you please run `bazel clean --expunge ; make install` and let me know when you have the latest `development` branch installed?

Cheers,
Chris

P.S: You want to make sure to call `env.close()` on any environments to tidy up the resources. Otherwise the python script can hang forever. For your trabular script, I'd suggest using a `try/finally`, and also re-using the same `env` instance for training (`gym.make()` is much slower than `env.reset()`):

```diff
diff --git a/examples/tabular_q.py b/examples/tabular_q.py
index ccc803e..04691c9 100644
--- a/examples/tabular_q.py
+++ b/examples/tabular_q.py
@@ -68,13 +68,12 @@ def get_max_q_value(q_table, ob):
     return max_q


-def train(q_table):
+def train(env, q_table):
     # Buffer an old version of q table to inspect training progress
     prev_q = {}

     for i in range(FLAGS.episodes):
         current_length = 0
-        env = get_env()
         obs = env.reset()
         # obs_prev = obs.copy()
         while current_length < FLAGS.episode_length:
@@ -120,19 +119,22 @@ def main(argv):
     setup_env()
     # Train a Q table.
     q_table = {}
-    train(q_table)
-    # Rollout based on the Max-Q policy.
     env = get_env()
-    ob = env.reset()
-    # Roll out one episode and report the resulting policy.
-    action_seq, rewards = [], []
-    for _ in range(FLAGS.episode_length):
-        a = select_action(q_table, ob)
-        action_seq.append(a)
-        ob, reward, done, info = env.step(env.action_space.flags.index(a))
-
-        rewards.append(reward)
-    print("Resulting sequence: ", ",".join(action_seq), f"total reward{sum(rewards)}")
+    try:
+        train(env, q_table)
+        # Rollout based on the Max-Q policy.
+        ob = env.reset()
+        # Roll out one episode and report the resulting policy.
+        action_seq, rewards = [], []
+        for _ in range(FLAGS.episode_length):
+            a = select_action(q_table, ob)
+            action_seq.append(a)
+            ob, reward, done, info = env.step(env.action_space.flags.index(a))
+
+            rewards.append(reward)
+        print("Resulting sequence: ", ",".join(action_seq), f"total reward{sum(rewards)}")
+    finally:
+        env.close()


 if __name__ == "__main__":
```

**Comment by ChrisCummins** [comment]
Hi @JD-ETH, I have made a change in #121 that enables the error message that is raised by a failed service init to contain logging output. Might be helpful to improve debugging. Feel free to take a look!

Cheers,
Chris

**Comment by JD-ETH** [comment]
The connection issue magically disappeared and I can't reproduce right now. I will mark this issue closed in this case. Thanks for your help!
