### ISSUE TITLE
Download error from eval_llvm_instcount_policy function

### ISSUE THREAD

**Issue by phesse001** [facebookresearch/CompilerGym#231]
Hello,

So I have a dqn model that I used with compiler_gym to apply code transformations to accomplish some objective (in this case instruction count). I was looking to use the `eval_llvm_instcount_policy()` on my model to see how well my model is doing and possibly submit it to the leaderboard.

I looked at a couple of the sample submissions, mainly the [tabular-q](https://github.com/facebookresearch/CompilerGym/tree/development/leaderboard/llvm_instcount/tabular_q) submission to use as a template. Based on this submission and the documentation I started by creating a basic function which takes an LLVM env as input and trains my dqn using this env. I then pass this function to the `eval_llvm_instcount_policy()` and there is a download that fails.

This is my terminal output after running the python file:

Traceback (most recent call last):
  File "dqn_policy.py", line 10, in <module>
    eval_llvm_instcount_policy(train_and_run)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/compiler_gym/leaderboard/llvm_instcount.py", line 317, in eval_llvm_instcount_policy
    app.run(main)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/compiler_gym/leaderboard/llvm_instcount.py", line 271, in main
    env = gym.make("llvm-ic-v0")
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/compiler_gym/envs/llvm/llvm_env.py", line 86, in __init__
    download_llvm_files()
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/compiler_gym/third_party/llvm/__init__.py", line 68, in download_llvm_files
    return _download_llvm_files(unpacked_location)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/compiler_gym/third_party/llvm/__init__.py", line 42, in _download_llvm_files
    tar_contents = io.BytesIO(download(url, sha256=sha256))
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/fasteners/process_lock.py", line 276, in wrapper
    return f(*args, **kwargs)
  File "/home/phesse/python-virtual-environments/compiler_gyWritim/lib/python3.8/site-packages/compiler_gym/util/download.py", line 51, in download
    content = _download(url)
  File "/home/phesse/python-virtual-environments/compiler_gym/lib/python3.8/site-packages/compiler_gym/util/download.py", line 19, in _download
    raise OSError(f"GET returned status code {req.status_code}: {url}")
OSError: GET returned status code 403: https://dl.fbaipublicfiles.com/compiler_gym/llvm-10.0.0-linux.tar.bz2

When I look at the [link](https://dl.fbaipublicfiles.com/compiler_gym/llvm-10.0.0-linux.tar.bz2) it is trying to download from, it says 'Access Denied' for the error.

Any help is appreciated - I can provide more details if needed and my code that I was referencing is [here](https://github.com/phesse001/compiler-gym-dqn/tree/leaderboard) if that helps.

Thanks!

**Comment by ChrisCummins** [comment]
Hi @phesse001, thanks for the report!

This is my fault. I renamed that file and forgot that older releases of CompilerGym will still attempt to download it. If you try again now the download should succeed.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Also just a heads up of a release issue with v0.1.7, you will also need to run:

```
pip install 'GPUtil>=1.4.0' 'psutil>=5.8.0' 'py-cpuinfo>=7.0.0' 'tqdm>=4.55.0'
```

See #167.

**Comment by ChrisCummins** [comment]
Closing this as I was able to verify the fix on colab. Please reopen if the problem persists :)

Cheers,
Chris
