### ISSUE TITLE
How to use our own data make env and save the environment states

### ISSUE THREAD

**Issue by Angerla** [facebookresearch/CompilerGym#354]
## ❓ Questions and Help

I want to use our own data to make the env and save the environment states but meet the problems:
```Traceback (most recent call last):
  File "test.py", line 22, in <module>
    writer.write_state(env.state)
  File "/root/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.1.8-py3.8.egg/compiler_gym/envs/compiler_env.py", line 360, in state
    return CompilerEnvState(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CompilerEnvState
benchmark
  string does not match regex "(?P<dataset>(?P<dataset_protocol>[a-zA-z0-9-_]+)://(?P<dataset_name>[a-zA-z0-9-_]+-v(?P<dataset_version>[0-9]+)))/(?P<benchmark_name>[^\s]+)$" (type=value_error.str.regex; pattern=(?P<dataset>(?P<dataset_protocol>[a-zA-z0-9-_]+)://(?P<dataset_name>[a-zA-z0-9-_]+-v(?P<dataset_version>[0-9]+)))/(?P<benchmark_name>[^\s]+)$)
```
## Additional Context
The version I used is 0.1.8 and here is the code:
```
benchmark = Benchmark.from_file("benchmark://test_suilt/misr","/tmp/stoke/MCTS/examples/lym/misr.bc" )
env = gym.make(
    "llvm-v0",
    benchmark=benchmark,
    observation_space="Autophase",
    reward_space="IrInstructionCountOz",
)
env.reset()
env.render()
with CompilerEnvStateWriter(open("results.csv", "wb")) as writer:
    writer.write_state(env.state)
```

**Comment by ChrisCummins** [comment]
Hi @Angerla, thanks for the question.

The name of the benchmark suite must contain a version tag such as "-v0". Try this:

```diff
- benchmark = Benchmark.from_file("benchmark://test_suilt/misr","/tmp/stoke/MCTS/examples/lym/misr.bc" )
+ benchmark = Benchmark.from_file("benchmark://test_suilt-v0/misr","/tmp/stoke/MCTS/examples/lym/misr.bc" )
```

Let me know if that works. I'll take a look at making that error message more descriptive :)

Cheers,
Chris

**Comment by Angerla** [comment]
Thanks, it helped.
