### ISSUE TITLE
[High priority] Building from source + all CI jobs failing, csmith archive checksum invalid

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#590]
## 🐛 Bug

*ALL* CI tests are currently in the red. The problem is that the csmith checksum has changed from ba871c1e5a05a71ecd1af514fedba30561b16ee80b8dd5ba8f884eaded47009f to 86d08c19a1f123054ed9350b7962edaad7d46612de0e07c10b73e578911156fd. This is blocking all CI tests and building from source!!

```
WARNING: Download from https://github.com/csmith-project/csmith/archive/refs/tags/csmith-2.3.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 86d08c19a1f[123](https://github.com/facebookresearch/CompilerGym/runs/5354537310?check_suite_focus=true#step:5:123)054ed9350b7962edaad7d46612de0e07c10b73e578911156fd but wanted ba871c1e5a05a71ecd1af514fedba30561b16ee80b8dd5ba8f884eaded47009f
ERROR: An error occurred during the fetch of repository 'csmith':
   Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/db3e34f1e14ee53d927a48b4c425fcaa/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/csmith-project/csmith/archive/refs/tags/csmith-2.3.0.tar.gz] to /home/runner/.cache/bazel/_bazel_runner/db3e34f1e14ee53d927a48b4c425fcaa/external/csmith/temp5123569277232776356/csmith-2.3.0.tar.gz: Checksum was 86d08c19a1f123054ed9350b7962edaad7d46612de0e07c10b73e578911156fd but wanted ba871c1e5a05a71ecd1af514fedba30561b16ee80b8dd5ba8f884eaded47009f
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/db3e34f1e14ee53d927a48b4c425fcaa/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/csmith-project/csmith/archive/refs/tags/csmith-2.3.0.tar.gz] to /home/runner/.cache/bazel/_bazel_runner/db3e34f1e14ee53d927a48b4c425fcaa/external/csmith/temp5123569277232776356/csmith-2.3.0.tar.gz: Checksum was 86d08c19a1f123054ed9350b7962edaad7d46612de0e07c10b73e578911156fd but wanted ba871c1e5a05a71ecd1af514fedba30561b16ee80b8dd5ba8f884eaded47009f
ERROR: /home/runner/work/CompilerGym/CompilerGym/compiler_gym/third_party/csmith/BUILD:16:15: //compiler_gym/third_party/csmith:csmith depends on @csmith//:all in repository @csmith which failed to fetch. no such package '@csmith//': java.io.IOException: Error downloading [https://github.com/csmith-project/csmith/archive/refs/tags/csmith-2.3.0.tar.gz] to /home/runner/.cache/bazel/_bazel_runner/db3e34f1e14ee53d927a48b4c425fcaa/external/csmith/temp5123569277232776356/csmith-2.3.0.tar.gz: Checksum was 86d08c19a1f123054ed9350b7962edaad7d46612de0e07c10b73e578911156fd but wanted ba871c1e5a05a71ecd1af514fedba30561b16ee80b8dd5ba8f884eaded47009f
```

![](https://c.tenor.com/eEs1jRy5UXgAAAAC/house-explosion.gif)

**Comment by mostafaelhoushi** [comment]
![image](https://user-images.githubusercontent.com/1451293/156421322-13e1067e-75b0-41e1-8ab8-2ff41fd23b9f.png)
