### ISSUE TITLE
Protobuf >= 4.21.0 is incompatible with CompilerGym wheel

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#696]
## 🐛 Bug

Protobuf has released a new major version with breaking changes. CompilerGym requires protobuf>=3.13.0, which means that a fresh install grabs protobuf 4.21. The problem only 

## To Reproduce

1. Install CompilerGym:
```
$ pip install compiler_gym
```
2. Bump your protobuf version:
```
$ pip install -U protobuf
```
3. Try and use CompilerGym:
```
$ python -c 'import compiler_gym'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/__init__.py", line 32, in <module>
    from compiler_gym.compiler_env_state import (
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/compiler_env_state.py", line 12, in <module>
    from compiler_gym.datasets.uri import BenchmarkUri
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/datasets/__init__.py", line 6, in <module>
    from compiler_gym.datasets.benchmark import (
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/datasets/benchmark.py", line 12, in <module>
    from compiler_gym.service.proto import Benchmark as BenchmarkProto
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/service/__init__.py", line 5, in <module>
    from compiler_gym.service.compilation_session import CompilationSession
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/service/compilation_session.py", line 8, in <module>
    from compiler_gym.service.proto import ActionSpace, Benchmark
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/service/proto/__init__.py", line 5, in <module>
    from compiler_gym.service.proto.compiler_gym_service_pb2 import (
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.2.4-py3.8.egg/compiler_gym/service/proto/compiler_gym_service_pb2.py", line 30, in <module>
    _GETVERSIONREQUEST = _descriptor.Descriptor(
  File "/private/home/cummins/.conda/envs/compiler_gym/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 313, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

## Expected behavior

```
$ python -c 'import compiler_gym'
<no output>
```

## Environment

Please fill in this checklist:

- CompilerGym: 0.2.3
- How you installed CompilerGym (pip, source): n/a
- OS: Linux
- Python version: 3.8

## Additional context

Thanks @hughleat for the report.

**Comment by ChrisCummins** [comment]
# Workaround

After installing CompilerGym, downgrade your version of protobuf:

```
$ pip install protobuf==3.17.0
```
