### ISSUE TITLE
How to modify the default llvm version 10 to 16?

### ISSUE THREAD

**Issue by sparks-code** [facebookresearch/CompilerGym#790]
## ❓ Questions and Help

Hello,ChrisCummins！ thank you again for your last help! 
I noticed the compiler_ The default compiler version used by Gym is 10. If I want to update it to 16 and possibly modify the action space, what do I need to do?

**Comment by ChrisCummins** [comment]
Hey @sparks-code sorry for the slow response.

Bumping to LLVM 16 will require code changes. The pass list will be a little different, and there may be some other API changes. To get you started, you could:

1. Build from source [using cmake](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#building-from-source-with-cmake) and an external version of LLVM 10 (as a sanity test).
2. Swap out to external LLVM 16 in your cmake config, try and build, iterate on build errors.
3. Update the action files in https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes/10.0.0 to the LLVM 16 pass list, adding any new ones and removing old ones.

Unfortunately there's no simple recipe for this. It may require some work. Hope that helps.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
We have a long term project to overhaul the build system in a way that would make it much easier to plug in different versions of LLVM (including custom forks), but sadly no bandwidth to work on this at the moment.

**Comment by sparks-code** [comment]
hello,@ChrisCummins.thanks for your advice. I'm already trying to upgrade the llvm version， but[https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/service/RunService.cc](url)this file generat  errors during the build process,
![image](https://user-images.githubusercontent.com/53423567/231462514-be335f00-5301-4bb9-b0a1-40bb0932645c.png)
In the new version of LLVM, some functions are gone. 
so So how should I change the initLlvm() function?



> Hey @sparks-code sorry for the slow response.
> 
> Bumping to LLVM 16 will require code changes. The pass list will be a little different, and there may be some other API changes. To get you started, you could:
> 
> 1. Build from source [using cmake](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#building-from-source-with-cmake) and an external version of LLVM 10 (as a sanity test).
> 2. Swap out to external LLVM 16 in your cmake config, try and build, iterate on build errors.
> 3. Update the action files in https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes/10.0.0 to the LLVM 16 pass list, adding any new ones and removing old ones.
> 
> Unfortunately there's no simple recipe for this. It may require some work. Hope that helps.
> 
> Cheers, Chris

**Comment by ChrisCummins** [comment]
Hi @sparks-code, good to here that you're making progress.

Is the build error happening when you switch the LLVM to 16? Does the build error happen using the default LLVM 10? If not, then it must be some change in LLVM's initialization routines. You could check the changelogs to see how those routines changed. Your best bet for help on LLVM-specific questions will be on their discord, I'm not an LLVM dev.

Cheers,
Chris

**Comment by cgao3** [comment]
> Hey @sparks-code sorry for the slow response.
> 
> Bumping to LLVM 16 will require code changes. The pass list will be a little different, and there may be some other API changes. To get you started, you could:
> 
> 1. Build from source [using cmake](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#building-from-source-with-cmake) and an external version of LLVM 10 (as a sanity test).
> 2. Swap out to external LLVM 16 in your cmake config, try and build, iterate on build errors.
> 3. Update the action files in https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes/10.0.0 to the LLVM 16 pass list, adding any new ones and removing old ones.
> 
> Unfortunately there's no simple recipe for this. It may require some work. Hope that helps.
> 
> Cheers, Chris

Hi Chris,  I followed all these steps. It appears that I can build the `whl` package, and reinstall via 
`pip install <path to build directory>/py_pkg/dist/compiler_gym*.whl --force-reinstall`

However, then I tried `env.reset` for `llvm-v0`. It gives errors. I am now puzzled by this error. do you have any clue on this?  thanks.

details here: https://github.com/facebookresearch/CompilerGym/issues/788#issuecomment-1531979923

**Comment by cgao3** [comment]
I tried to dive into it a little bit.. The `FileNotFoundError` is not informative.. I tried to use an existing `bc` for `reset`, still same error, where I am 100% certain the `bc` file is there..
```
>>> import os
>>> os.path.exists("/home/cgao3/qsort.bc")
True
>>> import compiler_gym
>>> env = compiler_gym.make("llvm-v0")
>>> env.compiler_version
'12.0.1 x86_64-unknown-linux-gnu'
>>> b = env.make_benchmark("/home/cgao3/qsort.bc")
>>> env.reset(benchmark=b)
Traceback (most recent call last):
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 760, in _reset
    error, reply = _call_with_error(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 695, in _call_with_error
    return None, self.service(stub_method, *args, **kwargs)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 813, in __call__
    return self.connection(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 217, in __call__
    raise FileNotFoundError(e.details()) from None
FileNotFoundError: Benchmark not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 201, in __call__
    return stub_method(request, timeout=timeout)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1683309164.001394705","description":"Error received from peer ipv6:[::1]:33199","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Connection reset by peer","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 695, in _call_with_error
    return None, self.service(stub_method, *args, **kwargs)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 813, in __call__
    return self.connection(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/connection.py", line 230, in __call__
    raise ServiceIsClosed("Service is offline")
compiler_gym.errors.service_errors.ServiceIsClosed: Service is offline

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/envs/llvm/llvm_env.py", line 366, in reset
    return super().reset(*args, **kwargs)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 624, in reset
    return self._reset(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 778, in _reset
    return _retry(error)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 681, in _retry
    return self._reset(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 778, in _reset
    return _retry(error)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 681, in _retry
    return self._reset(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 778, in _reset
    return _retry(error)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 681, in _retry
    return self._reset(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 778, in _reset
    return _retry(error)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 681, in _retry
    return self._reset(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 778, in _reset
    return _retry(error)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 681, in _retry
    return self._reset(
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 778, in _reset
    return _retry(error)
  File "/home/cgao3/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym/service/client_service_compiler_env.py", line 675, in _retry
    raise OSError(
OSError: Failed to reset environment using benchmark benchmark://file-v0/home/cgao3/qsort.bc after 4 attempts.
Last error (ServiceIsClosed): Service is offline
```

**Comment by ChrisCummins** [comment]
Followed up on #788.

**Comment by Wuyoo0203** [comment]
Hi, I'm doing the same job. Have you built successfully so far?

**Comment by Wuyoo0203** [comment]
> 你好，@ChrisCummins.谢谢你的建议。我已经在尝试升级 llvm 版本，但在构建过程中[https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/service/RunService.cc](url)此文件生成错误，在新版 LLVM 中，![image](https://user-images.githubusercontent.com/53423567/231462514-be335f00-5301-4bb9-b0a1-40bb0932645c.png)某些功能消失了。那么我应该如何更改 initLlvm（） 函数呢？
> 
> > 嘿，很抱歉反应缓慢。
> > 升级到 LLVM 16 将需要更改代码。传递列表会略有不同，并且可能会有一些其他 API 更改。要帮助您入门，您可以：
> > 
> > 1. [使用 cmake](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#building-from-source-with-cmake) 和 LLVM 10 的外部版本从源代码构建（作为健全性测试）。
> > 2. 在 cmake 配置中换出到外部 LLVM 16，尝试构建，迭代构建错误。
> > 3. 将 [https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes/10.0.0 中的](https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes/10.0.0)操作文件更新到 LLVM 16 传递列表，添加任何新文件并删除旧文件。
> > 
> > 不幸的是，没有简单的方法。这可能需要一些工作。希望有帮助。
> > 干杯，克里斯

Hi, I'm doing the same job. Have you built successfully so far?

**Comment by Wuyoo0203** [comment]
> hello,@ChrisCummins.thanks for your advice. I'm already trying to upgrade the llvm version， but[https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/service/RunService.cc](url)this file generat errors during the build process, ![image](https://user-images.githubusercontent.com/53423567/231462514-be335f00-5301-4bb9-b0a1-40bb0932645c.png) In the new version of LLVM, some functions are gone. so So how should I change the initLlvm() function?
> 
> > Hey @sparks-code sorry for the slow response.
> > Bumping to LLVM 16 will require code changes. The pass list will be a little different, and there may be some other API changes. To get you started, you could:
> > 
> > 1. Build from source [using cmake](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#building-from-source-with-cmake) and an external version of LLVM 10 (as a sanity test).
> > 2. Swap out to external LLVM 16 in your cmake config, try and build, iterate on build errors.
> > 3. Update the action files in https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes/10.0.0 to the LLVM 16 pass list, adding any new ones and removing old ones.
> > 
> > Unfortunately there's no simple recipe for this. It may require some work. Hope that helps.
> > Cheers, Chris

Hi, I'm doing the same job. Have you built successfully so far?

**Comment by sparks-code** [comment]
> Hi, I'm doing the same job. Have you built successfully so far?
I have upgraded, but the pass manager of llvm17 seems to be different from 10, and some passes have changed. If you are interested, you can add me on WeChat 17356055726 and communicate with me.

**Comment by Wuyoo0203** [comment]
> > Hi, I'm doing the same job. Have you built successfully so far?
> > I have upgraded, but the pass manager of llvm17 seems to be different from 10, and some passes have changed. If you are interested, you can add me on WeChat 17356055726 and communicate with me.

Okay, I got it. Thank you.

**Comment by zcfh** [comment]
How to modify the binary downloaded by `~/.local/share/compiler_gym/llvm-v0`, I build compile_gym through llvm11, I manually replace the llvm-0 downloaded by compiler_gym with the binary of llvm-11, the .bc file generated by llvm_wrapper is not available Use (the final generated binary has runtime problems)
