### ISSUE TITLE
Build fails with external LLVM behind proxy

### ISSUE THREAD

**Issue by saqibameen** [facebookresearch/CompilerGym#793]
## ❓ Questions and Help

I am trying to build CompilerGym with an external version of LLVM 10 using CMake as described in the documentation. I am behind company's vpn with `https_proxy` and `http_proxy` set, it is giving error: "unable to find valid certification path to requested target".

```sh
INFO: Repository com_github_nelhage_rules_boost instantiated at:
  /home/saqib/code/compilerGymBuild/external/programl/programl/src/programl/WORKSPACE:6:14: in <toplevel>
  /home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/programl/tools/bzl/deps.bzl:14:15: in programl_deps
Repository rule http_archive defined at:
  /home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/nelhage/rules_boost/archive/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'com_github_nelhage_rules_boost':
   Traceback (most recent call last):
        File "/home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/nelhage/rules_boost/archive/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz] to /home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/com_github_nelhage_rules_boost/temp487127642318174362/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/nelhage/rules_boost/archive/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz] to /home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/com_github_nelhage_rules_boost/temp487127642318174362/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@com_github_nelhage_rules_boost//boost': java.io.IOException: Error downloading [https://github.com/nelhage/rules_boost/archive/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz] to /home/saqib/.cache/bazel/_bazel_saqib/21578fea1d5adb233383680525cbb5c5/external/com_github_nelhage_rules_boost/temp487127642318174362/4ee400beca08f524e7ea3be3ca41cce34454272f.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by ChrisCummins** [comment]
Hmm, I don't have the expertise to weigh in on this, I'm afraid. The only suggestion I could make would be to mirror that URL which is failing to download to some other site which works with your firewall. Sorry I can't help!

Cheers,
Chris
