### ISSUE TITLE
compiler_gym.errors.service_errors.ServiceError

### ISSUE THREAD

**Issue by 18liumin** [facebookresearch/CompilerGym#813]
>>> compiler_gym.COMPILER_GYM_ENVS
['gcc-v0', 'llvm-v0', 'llvm-ic-v0', 'llvm-codesize-v0', 'llvm-autophase-ic-v0', 'llvm-autophase-codesize-v0', 'llvm-ir-ic-v0', 'llvm-ir-codesize-v0', 'loop_tool-v0']
>>> env = gym.make("llvm-autophase-ic-v0")
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 1)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 2)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 3)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 4)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = cls(**_kwargs)
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/compiler_gym/envs/llvm/llvm_env.py", line 334, in __init__
    "token_value": [],
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/compiler_gym/service/client_service_compiler_env.py", line 210, in __init__
    opts=self._connection_settings,
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/compiler_gym/service/connection.py", line 646, in __init__
    self._establish_connection()
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/compiler_gym/service/connection.py", line 657, in _establish_connection
    self.connection = self._create_connection(self.endpoint, self.opts)
  File "/usr1/l00683357/anaconda3/envs/python3/lib/python3.7/site-packages/compiler_gym/service/connection.py", line 719, in _create_connection
    f"Failed to create connection to {endpoint_name} after "
compiler_gym.errors.service_errors.ServiceError: Failed to create connection to compiler_gym-llvm-service after 0.5 seconds (5 attempts made).
Last error (ServiceError): Service terminated with returncode: 127

**Comment by avithemad** [comment]
Is this repository no longer active? I just went through the getting started and I get this same issue. 
LLVM should work out of the box right
@ChrisCummins

**Comment by ChrisCummins** [comment]
Apologies @avithemad, I've had a lot on my plate recently and CompilerGym work has had to take a backseat. Sorry about this, you're right, LLVM should work right out of the box. I'll hopefully get around to taking a look at this issue soon.

Cheers,
Chris

**Comment by avithemad** [comment]
No issues, thanks for the reply. I hope it goes well. 
Is there a future plan to support mlir based compilers as well?
