### ISSUE TITLE
[validation] Timeout during LLVM environment reset()

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#99]
## 🐛 Bug

Running validaiton on the attached results set causes timeout errors during environment reset with an unhelpful error message.

## To Reproduce

Run validation on this dataset: [results.csv.zip](https://github.com/facebookresearch/CompilerGym/files/6049231/results.csv.zip)

```
$ bazel run -c opt //compiler_gym/bin:validate -- --env=llvm-ic-v0 results.csv
INFO: Analyzed target //compiler_gym/bin:validate (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //compiler_gym/bin:validate up-to-date:
  bazel-bin/compiler_gym/bin/validate
INFO: Elapsed time: 0.301s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/compiler_gym/bin/validate '--env=llvm-ic-v0' /home/cec/data/compiler_gym/leaderboard/l
INFO: Build completed successfully, 1 total action
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/adpcm                           1.0000
✅  cBench-v0/adpcm                           1.0000
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/adpcm                           1.0000
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/adpcm                           1.0041
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/bitcount                        1.0141
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/blowfish                        1.0352
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/crc32                           1.0000
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/bzip2                           1.0322
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/dijkstra                        1.0194
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/ispell                          1.0005
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/jpeg-d                          1.0218
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/gsm                             1.1495
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/lame                            1.1138
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/patricia                        0.9693
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/qsort                           1.0292
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/rijndael                        1.1148
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/sha                             1.5532
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/jpeg-c                          1.0229
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/stringsearch                    1.0143
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/stringsearch2                   0.9742
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/susan                           1.0061
✅  cBench-v0/tiff2bw                         1.0044
✅  cBench-v0/tiff2bw                         1.0044
✅  cBench-v0/tiff2bw                         1.0044
✅  cBench-v0/patricia                        0.9693
51 remaining states to validate ... multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/cec/anaconda3/envs/compiler_gym/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/validate.py", line 22, in _validate_states_worker
    result = env.validate(state)
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/envs/compiler_env.py", line 972, in validate
    fkd = self.fork()
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/envs/compiler_env.py", line 499, in fork
    self.reset()
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/envs/compiler_env.py", line 637, in reset
    reply = self.service(
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/service/connection.py", line 627, in __call__
    return self.connection(
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/service/connection.py", line 208, in __call__
    raise TimeoutError(
TimeoutError: Deadline Exceeded (300.0 seconds)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/bin/validate.py", line 292, in <module>
    app.run(main)
  File "/home/cec/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/cec/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/bin/validate.py", line 258, in main
    for i, result in enumerate(validation_results, start=1):
  File "/mnt/cache/cec/bazel/_bazel_cec/932e895778ce021fb3c14db8871e2059/execroot/CompilerGym/bazel-out/k8-opt/bin/compiler_gym/bin/validate.runfiles/CompilerGym/compiler_gym/validate.py", line 67, in validate_states
    yield from map_func(
  File "/home/cec/anaconda3/envs/compiler_gym/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TimeoutError: Deadline Exceeded (300.0 seconds)
bazel run -c opt //compiler_gym/bin:validate -- --env=llvm-ic-v0   1490.37s user 373.11s system 487% cpu 6:22.24 total
```

## Expected behavior

Helpful error message and for the validation script to complete.

## Environment

Please fill in this checklist:

- CompilerGym: v0.1.2
- How you installed CompilerGym (conda, pip, source): source
- OS: Pop OS 20.04
- Python version: 3.8
- Build command you used (if compiling from source): bazel
- GCC/clang version (if compiling from source): gcc 10.2.0
- Bazel version (if compiling from source): 3.1.0

**Comment by ChrisCummins** [comment]
Added retry loop on timeout for `reset()`. Will re-open if able to repro.
